[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "st-microservice"
version = "0.11.5a"
authors = [
    {name = "Robert Trad", email = "roberttrad@gmail.com" }
]
description = "Tools to build Microservice Backends"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent"
]
dependencies = [
    "ariadne==0.17.0",
    "starlette<1",
    "websockets<11",
    "PyJWT>=2.1,<3",
    "sqlalchemy>=2.0b,<3",
    "pyparsing>=3.0,<4",
    "aiodataloader<1",
    "uvicorn>=0.20",
    "gunicorn>=20.0",
    "uvloop>=0.17;sys_platform=='linux'"
]

[project.urls]
"Homepage" = "https://github.com/rouppart/ST-Microservice"