[tool.poetry]
name = "iotree"
version = "0.1.3"
description = "A lightweight CLI + lib that allows you to perform basic IO tasks and display your content as rich trees and tables."
authors = ["Arno V <bcda0276@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
rich = ">=10.11.0,<13.0.0"
typer = {extras = ["all"], version = "^0.7.0"}
pyyaml = "^6.0"
toml = "^0.10.2"
pytest = "^7.2.0"
xmltodict = "^0.13.0"
httpx = {version = "^0.22.0", source = "pypi"}

[tool.poetry.scripts]
iotree = "iotree.__main__:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
