[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
#name = "cis_checks_6"
#version = "0.0.7"
name = "cis_checks_7"
version = "0.0.8"
authors = [
  { name="dheeraj.banodha", email="dheerajmbanodha@gmail.com" },
]
description = "Provides AWS compliance details"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

#[project.urls]
#"Homepage" = ""
#"Bug Tracker" = ""