[package]
name = "pysqlx-core"
version = "0.1.31"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

include = [
    "/pyproject.toml",
    "/LICENSE",
    "/README.md",
    "/convert",
    "/database",
    "/py_types",
    "/pysqlx_core.pyi",
    "/src"
]

[lib]
name = "pysqlx_core"
crate-type = ["rlib", "cdylib"]


[package.metadata.maturin]
python-source = "pysqlx_core"

[dependencies]
pyo3 = { version = "0.17", features = ["extension-module"] }
pyo3-asyncio = { version = "0.17", features = ["tokio-runtime"] }
env_logger = "0.10"

# my packages
py_types = { path = "local_dependencies/py_types" }
convert = { path = "local_dependencies/convert" }
database = { path = "local_dependencies/database" }

[workspace]
members = ["local_dependencies/convert", "local_dependencies/database", "local_dependencies/py_types"]
