[tool.poetry]
name = "sentry-dynamic-sampling-lib"
version = "1.1.0-alpha.3"
description = ""
authors = ["jeanloup.monnier <jean-loup.monnier@spikeelabs.fr>"]
readme = "README.md"
packages = [{include = "sentry_dynamic_sampling_lib"}]

[tool.poetry.dependencies]
python = "^3.9"
schedule = "^1.1.0"
wrapt = "^1.14.1"
psutil = "^5.9.4"
requests-cache = "^0.9.7"


[tool.poetry.group.dev.dependencies]
bandit = "^1.7.4"
black = "^22.12.0"
coverage = "^7.0.4"
pre-commit = "^2.21.0"
pylama = "^8.4.1"
pylint = "^2.15.9"
toml = "^0.10.2"
sentry-sdk = "^1.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
