[package]
name = "rakun_python"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rakun_python"
crate-type = ["cdylib"]

[dependencies]
async-std = "1.12.0"
pyo3 = { version = "0.17.3", features = ["extension-module"] }
pyo3-asyncio = { version = "0.17", features = ["async-std-runtime"] }
