[tool.poetry]
name = "getting-and-setting"
version = "0.5.4"
description = "An interface to interact with the Ion Mi Api."
authors = ["Kim Timothy Engh <kimothy@users.noreply.github.com>"]
license = "GPL3.0"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
keyring = "^23.5.1"
tabulate = "^0.8.9"
typer =  "^0.4.1" 

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
micli = "getting_and_setting.mi_cli:app"