[tool.poetry]
name = "pymbse"
version = "0.0.22"
description = ""
authors = ["mmaciejewski <michal.maciejewski@ief.ee.ethz.ch>"]

[tool.poetry.dependencies]
python = "^3.9"
pymbse-commons = "^0.0.6"
pydantic = "^1.9.1"
PyYAML = "^6.0"
papermill = "^2.3.4"
scrapbook = "^0.5.0"
nbconvert = "^6.5.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-mock = "^3.8.2"
pytest-cov = "^3.0.0"
responses = "^0.21.0"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
