[tool.poetry]
name = "uptick-datawarehouse"
version = "0.1.5"
description = ""
authors = ["william chu <william.chu@uptickhq.com>"]
readme = "public_readme.md"

packages = [{ include = "app" }, { include = "uptick_datawarehouse" }]
exclude = ["app"]


[tool.poetry.dependencies]
python = "^3.10"
django = ">=3.2, <5.0.0"
dsnparse = "^0.1.15"
dj-database-url = "^1.2.0"
psycopg2 = "^2.9.5"
django-extensions = "^3.2.1"


[tool.poetry.group.dev.dependencies]
django-extensions = "^3.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
