title = "nRobo - Automated Testing Framework By Ndi"

[owner]
name = "Panchdev Singh Chauhan"

authors = [
    { name = "Panchdev Chauhan", email = "erpanchdev@gmail.com" }
]

[project]
name = "nrobo"
description = "nRobo - Automated Testing Framework By Ndi"
readme = "README.rst"
version = "1.0.7"
keywords = ["test automation", "test automation framework", "automated testing", "automation testing", "testing", "qa", "acceptance test", "automation"]
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Software Development :: Testing :: Acceptance",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Testing :: Unit",
    "Operating System :: MacOS",
    "Operating System :: Unix",
    "License :: Freeware",
    "Intended Audience :: Developers",
    "Intended Audience :: Other Audience",
    "Intended Audience :: Information Technology",
    "Framework :: Pytest"
]

include = ["CHANGELOG.rst"]

dependencies = [
    "pytest"
]

[project.optional-dependencies]
dev = [
    "pytest"
]


[project.urls]
"Homepage" = "https://pypi.org/project/nrobo/"
"Bug Tracker" = "https://github.com/pancht/speedboat/issues"
"changelog" = "https://github.com/pancht/speedboat/blob/master/nrobo/CHANGELOG.md"

[project.scripts]
nrobo = "nrobo:launch"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"